### ISSUE TITLE
two youtrack instances example

### ISSUE THREAD

**Issue by huglester** [Egregors/youtrack-docker-compose#14]
Hello

do you have an example of docker-compose.yml file with one traeffic and two instances of youtrack on same machine?

Thanks

**Comment by egregors** [comment]
Hi! It looks like you can't do that. JB made YouTrack stateful. The app container contains data store within with possibility to make mapping to host machine. That means, if you run a few YouTrack instances with the same mapping, they will rewrite each other's changes. 

> The YouTrack image is a stateful container. This allows the databases, log files, configuration files, and application data to be stored and maintained even if the container is restarted or moved to a different host.

To be sure, you can check official documentation of YouTrack out: https://www.jetbrains.com/help/youtrack/server/youtrack-docker-installation.html#create-and-configure-directories

**Comment by huglester** [comment]
But editing .yml file I could add second row of youtrack2 image

with different volumes. 

I believe it should be possible, just the configuration issue

**Comment by egregors** [comment]
Yep, in this case, you can do that for sure. Looks like I got your question in the wrong way. I thought you want to make some sort of scaling (running N+1 instances of YouTrack with the same state store). 

I'll check, if I can add multiple YouTrack example in the repo.

**Comment by egregors** [comment]
So, you generally can do that by setting different `VIRTUAL_HOST`s. 

1. Change your `docker-complose` to smth like this: 
```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/srv/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  youtrack1:
    image: jetbrains/youtrack:2020.2.7479
    container_name: "youtrack1"
    volumes:
      - /srv/youtrack1/data:/opt/youtrack/data
      - /srv/youtrack1/conf:/opt/youtrack/conf
      - /srv/youtrack1/logs:/opt/youtrack/logs
      - /srv/youtrack1/backups:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.youtrack1.loadbalancer.server.port=8080"
      - "traefik.http.routers.youtrack1.rule=Host(`${VIRTUAL_HOST_1}`)"
      - "traefik.http.routers.youtrack1.entrypoints=websecure"
      - "traefik.http.routers.youtrack1.tls.certresolver=myresolver"

  youtrack2:
    image: jetbrains/youtrack:2020.2.7479
    container_name: "youtrack2"
    volumes:
      - /srv/youtrack2/data:/opt/youtrack/data
      - /srv/youtrack2/conf:/opt/youtrack/conf
      - /srv/youtrack2/logs:/opt/youtrack/logs
      - /srv/youtrack2/backups:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.youtrack2.loadbalancer.server.port=8080"
      - "traefik.http.routers.youtrack2.rule=Host(`${VIRTUAL_HOST_2}`)"
      - "traefik.http.routers.youtrack2.entrypoints=websecure"
      - "traefik.http.routers.youtrack2.tls.certresolver=myresolver"
```

2. Add `VIRTUAL_HOST_1` and `VIRTUAL_HOST_2` into `.env`
