### ISSUE TITLE
How can i add some another site to it?

### ISSUE THREAD

**Issue by IzaGz** [Egregors/youtrack-docker-compose#8]
Usually i used jwilder/nginx-proxy with jrcs/letsencrypt-nginx-proxy-companion
with this at the end  
```
networks:
  default:
    external:
      name: nginx-proxy
```
And in my docker-compose file for project i used to add something like
```
    environment:
      VIRTUAL_HOST: www.siteaddress.com, siteaddress.com
      LETSENCRYPT_HOST: www.siteaddress.com, siteaddress.com
      LETSENCRYPT_EMAIL:  email@email.com

```
and
 ```
networks:
  default:
    external:
      name: nginx-proxy

```

at the end of projects docker-compose

.
How can i do this with this youtrack config?
